### ISSUE TITLE
Persistent Settings/State

### ISSUE THREAD

**Issue by jgibbon** [zwieberl/harbour-fishtheke#11]
I'd like some kind of persistant storage for simple things like Settings or State.
**Things this could be useful for**:
 - (Setting) remember favourite video player as proposed in #9 
 - (State) remember last used search. Or possibly even a short history of the last x search parameters. This would be a topic for a new feature request, if you like the thought of it.

**Possible ways to do it**
 - QML: [nemo-qml-plugin-configuration](https://sailfishos.org/develop/docs/nemo-qml-plugin-configuration/). 
 - QML: [LocalStorage](https://github.com/jgibbon/Talefish/blob/master/qml/lib/PersistentObject.qml). I used this in slumber/Talefish. While it works really well and is easily extended for new Options with multiple types, some may see it as weird. 
 - C++: [QSettings](http://doc.qt.io/qt-5/qsettings.html). This suffers from missing change notifications IIRC. I have only marginal Experience with this, mostly because I am not the best C++ developer.

What do you think? Which would be your preferred way? 

cheers!

**Comment by zwieberl** [comment]
I'm not yet convinced of the need of a persistent storage. 

I personally would have integrated #9 (assuming it can be solved at all :-) ) with a combobox on the URL like:
* Copy to clipboard
* Open in browser
* Send to Videoplayer
* Send to Jupii
...

Search-history might be useful, but my personal usage of the app does not really require it.
Also, I haven't gotten any requests in the store about such a feature.

What I got are multiple requests to do something like #9 (or more general: Sending around the URLs to other apps). So I think, that issue should be solved first. 
Once we can send the URL to numerous places and the combobox gets cluttered up, then a storage might be the solution.

But I would appreciate any help on that front as well!

**Comment by zwieberl** [comment]
In light of #12 (Download files), persistent storage for settings might come in handy now. 
Here is what I have thought would be useful:
Settingspage with one checkbox "Ask for download location every time"
Below a textbox with a predefined download path (if above checkbox is deactiavted)
And finally a checkbox "Show download manager upon starting a download". 

I will hopefully integrate a download manager soon, then replace the "About"-Page with an Settings-Page, which could then utilize a persistent storage. 

If you are still willing to help on this front, that would be very much appreciated!

**Comment by jgibbon** [comment]
While I'm a bit short on time, I can prepare something for you if I find some.
Which of the methods described in the first comment would you prefer? 

I could 'port' my LocalStorage thing in a relatively short time. If you put a "global" Component at app level, you could set/get values from basically everywhere and get change notifications. They'd be persisted automatically when the application is closed normally ("onDestruction" isn't called if the application crashes or is killed), or one could persist them manually. Data is saved in sqlite in the applications config directory with this one. Because of time constraints (and because it did work well for my apps for years), I'd lean to this one, what do you think?

cheers

**Comment by zwieberl** [comment]
There is no hurry. I think, i will release a new version without downloads first, anyways. 
Then I have to implement downloading, which is a bit more work. 
After that we can see about storage. In the meantime I will also try to get a better look at all the options you gave above.

**Comment by zwieberl** [comment]
Well, since downloading will now be managed by vodman, instead of fishtheke itself, there also is no need for a peristent storage anymore.
I think, I will close this for now until a need arises again. Feel free to let me know, I can also reopen it immediately.
