### ISSUE TITLE
Add ability to download files

### ISSUE THREAD

**Issue by zwieberl** [zwieberl/harbour-fishtheke#12]
Wish from comments-section in harbour:
"Please add easy downloading of the videos."

Edit: Probably need to steal [DownloadManager from Webcat](https://github.com/llelectronics/webcat/blob/702b2d36059bcb696d77a4fdc94c8e0f99873e5b/src/DownloadManager.cpp)

**Comment by bonanza123** [comment]
Forgive my ignorance and complete uselessness with respect to Qt and QML, but what about something like https://forum.qt.io/topic/80732/quickdownload-easy-file-download-with-qt-qml-and-c ? Would that have any advantage over webcat's implementation?

**Comment by zwieberl** [comment]
Sorry for the late response. Busy holidays and all... 
I have seen the one you quoted as well. They look pretty similar. Will have to test which one works better.

**Comment by zwieberl** [comment]
VODman just came online in harbour. This could be a very nice solution for this whole topic, unfortunately it currently doesn't support direct downloading of video-URLs. I reached out to the author. Maybe we can cooperate on this one. Would be better than to reimplement this feature over and over again in different apps.

**Comment by zwieberl** [comment]
Vodman got a dbus-interface, which I implemented in fishtheke already to send URLs to Vodman. So it should work in theory, but only after a new vodman and fishtheke-version comes online in harbour, thus I will close the issue.
