### ISSUE TITLE
Change handling of locked pulley menu

### ISSUE THREAD

**Issue by Pohli** [zwieberl/harbour-fishtheke#14]
If the pulley menu on the results page is locked it can't be pulled up but it's still indicated. I think this is irritating. Better let the pulley menu always be accessible but grey out the menu option if it should not be selectable.

**Comment by zwieberl** [comment]
True.
But I find menus without options somewhat irritating as well. I will check, if I can remove the indicator altogether, if nothing can be fetched. 
Would that be ok?

**Comment by Pohli** [comment]
Sounds even better!
