### ISSUE TITLE
Make filters editable

### ISSUE THREAD

**Issue by Pohli** [zwieberl/harbour-fishtheke#15]
I often need to adjust search terms due to insufficient search results. For that I have to remove the current filter and add a new one. It would be easier to just edit the current filter.

**Comment by zwieberl** [comment]
I was afraid someone was going to ask for this sooner or later :-) 
I will look into it!

**Comment by Pohli** [comment]
Thanks, that was quick!

**Comment by zwieberl** [comment]
Would have been even quicker (or there from the very beginning) if QML and JS weren't such terrible, terrible languages ;-)
