### ISSUE TITLE
Show version number inside app

### ISSUE THREAD

**Issue by Pohli** [zwieberl/harbour-fishtheke#7]
See title.

**Comment by zwieberl** [comment]
I haven't found a convenient location to place an "About"-page yet, so I omitted it for now.
Would it suffice to put the version number into the Cover-screen (when "minimizing" the app)?

**Comment by Pohli** [comment]
On Cover would be very uncommon IMO. Why not just simply add an option to the pulley menu at search page? (at upmost position of course)

**Comment by zwieberl** [comment]
I like the swiftness of just pulling down without "aiming" to add a filter. With the option for an About-page there, this has to be done slower and with care. 

But given the need of an About-page (need also one to give credit for the upcoming icon), I will probably have to go for the pulldown-menu.

**Comment by Pohli** [comment]
I've seen pullup menus from the bottom as well.

**Comment by zwieberl** [comment]
True. But with both pullup and pulldown menues on one page, the page gets very "wobbly". I will experiment a bit, which is better.
